service: sso
runtime: nodejs20
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.85
  min_instances: 1
  max_instances: 1
  max_concurrent_requests: 80

handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  # this could be production or staging or dev depending on your setup
  NODE_ENV: "production"
  SESSION_SECRET: "{{ session_secret }}"
  GCS_BUCKET_NAME: "{{ gcs_bucket_name }}"

entrypoint: node app.js